name: Package Updater
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      accesToken:
        required: true
      spaceId:
        required: true

jobs:
  Update_Packages:
    runs-on: ubuntu-latest
    steps:
      # Checkout the main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.FORMATTER_TOKEN }}
          submodules: recursive
      # if the main branch hasn't been updated in a while, set REPO_STALE to true
      - name: Check for updates
        run: |
          if [ $(git log --since="3 days ago" | wc -l) -eq 0 ]; then
            echo "REPO_STALE=true" >> $GITHUB_ENV
          fi
      # run npm-check-updates to update package.json and save the output
      - name: Update package.json
        if: env.REPO_STALE != 'true'
        run: |
          echo "Updating package.json"
          echo "UPDATES<<EOF" >> $GITHUB_ENV
          npx npm-check-updates -u >> $GITHUB_ENV
          npx @antfu/ni --no-frozen-lockfile
          echo "EOF" >> $GITHUB_ENV
      # diff the current package.json against the one in the package-updates branch
      # if there aren't any differences, exit the workflow
      - name: Diff package.json
        if: env.REPO_STALE != 'true'
        run: |
          if git diff --exit-code main origin/package-updates -- package.json; then
            echo "No changes to package.json"
            echo "NO_CHANGES=true" >> $GITHUB_ENV
          fi
      # Create a PR from the package-updates branch to the main branch if it doesn't exist
      - name: Create PR
        if: env.REPO_STALE != 'true' && !env.NO_CHANGES
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          token: ${{ secrets.FORMATTER_TOKEN }}
          title: Combined Package Updates
          base: main
          branch: package-updates
          commit-message: Update Packages
          body: |
            The following packages have been updated:
            ${{ env.UPDATES }}
      - name: Enable PR auto-merge
        if: env.REPO_STALE != 'true' && !env.NO_CHANGES
        continue-on-error: true
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.FORMATTER_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
