name: Code Checks
on:
  workflow_call:
    secrets:
      SECRETS_JSON:
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Check_Formatting:
    runs-on: ubuntu-latest
    steps:
      # BEGIN INSTALLATION
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: .nvmrc
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install
      # END INSTALLATION

      - name: format
        run: npm run format > /dev/null
        continue-on-error: true
      - name: Check for changes and commit
        run: |
          if git diff --exit-code; then
            echo "No changes detected"
            exit 0
          fi
          if git diff --exit-code --ignore-submodules; then
            echo "You have unformatted code in your submodules"
            exit 1
          fi
          echo "You have unformatted code!"
          git diff
          exit 1

  Generate_Types:
    # install modules, run a build, then cache and upload so we can use in other builds
    runs-on: ubuntu-latest
    needs: Check_Formatting
    steps:
      - name: Load .env file
        uses: shine1594/secrets-to-env-action@master
        with:
          secrets: ${{ secrets.SECRETS_JSON }}
          secrets_env: all
      # BEGIN INSTALLATION
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: .nvmrc
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install
      # END INSTALLATION

      - name: Build
        run: npm run build
      - name: Cache generated-types
        uses: actions/cache@v2
        with:
          path: src/types/gatsby-types.d.ts
          key: ${{ runner.os }}-generated-types-${{ github.sha }}
      - name: Upload Generated Types
        uses: actions/upload-artifact@v2
        with:
          name: generated-types
          path: src/types/gatsby-types.d.ts

  Check_Linting:
    runs-on: ubuntu-latest
    needs: Generate_Types
    steps:
      # BEGIN INSTALLATION
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: .nvmrc
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install
      # END INSTALLATION

      - name: Fetch Generated Types
        uses: actions/download-artifact@v2
        with:
          name: generated-types
      - name: Lint
        run: npm run lint

  Type_Checking:
    runs-on: ubuntu-latest
    needs: Generate_Types
    steps:
      # BEGIN INSTALLATION
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: .nvmrc
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install
      # END INSTALLATION

      - name: Fetch Generated Types
        uses: actions/download-artifact@v2
        with:
          name: generated-types
      - name: Check types
        run: npx tsc --noEmit
