name: Package Updater
# run daily at noon MST
on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  Update_Packages:
    runs-on: self-hosted
    steps:
      # Checkout the main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.FORMATTER_TOKEN }}
      # run npm-check-updates to update package.json and save the output
      - name: Update package.json
        run: |
          echo "Updating package.json"
          echo "UPDATES<<EOF" >> $GITHUB_ENV
          npx npm-check-updates -u >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      # diff the current package.json against the one in the package-updates branch
      # if there aren't any differences, exit the workflow
      - name: Diff package.json
        run: |
          if git diff --exit-code main package-updates -- package.json; then
            echo "No changes to package.json"
            echo "NO_CHANGES=true" >> $GITHUB_ENV
          fi
      # Create a PR from the package-updates branch to the main branch if it doesn't exist
      - name: Create PR
        if: ${{ !env.NO_CHANGES }}
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          token: ${{ secrets.FORMATTER_TOKEN }}
          title: Combined Package Updates
          base: main
          branch: package-updates
          commit-message: Update Packages
          body: |
            The following packages have been updated:
            ${{ env.UPDATES }}
      - name: Enable PR auto-merge
        if: ${{ !env.NO_CHANGES }}
        continue-on-error: true
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.FORMATTER_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
